#!/usr/bin/env bash
##script redirects user to alueducation.com

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.alueducation.com/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart

